### ISSUE TITLE
Wrong gender

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#10]
Some of the race results with no CSV have everyone as male eg 16848. This is wrong on CTT so will have to check other races for these riders and see if they really are male or not.

**Comment by drnickw** [comment]
Process now validates gender using the CSV as priority.
However riders with no CSV files for any races can still be wrong. 
I`m considering a database of girls names to cross reference with

**Comment by rogernclarke** [comment]
Are you happy enough to close this one now?

**Comment by drnickw** [comment]
I still intend to do the cross reference list and update the riders, it will be quicker than doin it all by hand. It’s on my jobs list.

**Comment by drnickw** [comment]
I now have a table of girls names! Gender will be best I can do next time I run.
