### ISSUE TITLE
Event data - event name tidying

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#13]
Candidate suggestions for test within brackets to be stripped out if it contains:

- "cheques"
- "entries"
- "under 17"
- "%"
- "ages"

I think these would be safe to action. There may be more that should be applied.

Separately we will need to think of how the event names can be made more presentable in terms of case. It looks like CTT make the first character of each word upper case, so that might be a start.

**Comment by drnickw** [comment]
event_name <- sub("(fee per rider)","",event_name,ignore.case = TRUE)
  event_name <- sub("(entries close.*)","",event_name,ignore.case = TRUE)  
  event_name <- sub("(cheques.*)","",event_name,ignore.case = TRUE)
  event_name <- sub("(chq.*)","",event_name,ignore.case = TRUE)
  event_name <- sub("(preference.*)","",event_name,ignore.case = TRUE)
  event_name <- sub("(entry fee.*)","",event_name,ignore.case = TRUE)
These are the bracketed fields I had arranged to remove. There is a problem with the code which seems to leave the first bracket at present which I`ll have to look into. I didnt want to remove age references as it may be a ditinguishing feature of two very similar events: although my processing will combine them if they are too short for ranking purposes this wont be evident in the DB

**Comment by rogernclarke** [comment]
The under 17 suggestion is to catch the GHS events which all have (under 17 on 31st August). That was added to all GHS events at my request years ago after Danny Winthoepe entered! The text doesn't add anything to the event name.
% is worth a look I think as it seems to be used to indicate a minimum percentage reserved for women - not sure if that is significant enough to keep. Similar to the preference conditions.

**Comment by drnickw** [comment]
Got all these now, except one which isnt in brackets and is too risky to try and remove.

**Comment by rogernclarke** [comment]
Looks an awful lot better!
What did you think about removing the %?
Spotted that "championship entry form" is another contender.
Do you have a Title Case setting that can put the start of each word as a capital letter?

**Comment by drnickw** [comment]
Pretty sure there are no % left on the eventsdb. (i think there was 1 not in brackets) I`ve bined lots of other unnecessary data too (including championship entry forms) in the DB /events version but its still in the rides CSV, although you`ll never pick that data up.

**Comment by rogernclarke** [comment]
I can see them on the website events page...

**Comment by drnickw** [comment]
Ooops - the code was working, must have sent an older file to the database which got rid of all ages too but they have re appeared. leave it with me.

**Comment by drnickw** [comment]
Yes, that was an old version - sent early on 21st looking at the processed date.
I did resend it but it didnt overwrite. How can i best delete and replace it as ths would seem advantageous during testing even if not when live? Will overwrite = true work here or should i delete it in cpanel?

**Comment by rogernclarke** [comment]
Feel free to try the overwrite=true but if it doesn't work you can use phpmyadmin in cpanel to delete all the rows. Something like delete * from tt_events

**Comment by rogernclarke** [comment]
I think the removal of text is about as good as you will get. Looking at last 100 events on events list shows three with anomalies where brackets haven't been opened or closed properly, but hard to deal with that I think.

There is one event that has (Closing date xxx).

I think there is a further improvement on display of event names that we could do - maybe something you could look at if my tasks take longer than anything you have left...

If each word started with a capital letter (except for those words in brackets. The only thing to handle with that would be acronyms such as VTTA, CC, RT. Can a list of most common acronyms be built to capitalise in conjunction with capitalizing first letters? I think that combination would look very neat.

**Comment by drnickw** [comment]
I`ve tidied up the names and removed some more stuff.
I`ll have a look at capitals and acronyms if i get a chance but may end up being release 2!
