### ISSUE TITLE
Rider District

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#23]
My preference is for a district_code column in the Riders table calculated and populated in R. There is a reason for this - we don't have the club_id in our data so we don't have the key field to reliably look up the club. The club name text can (in theory) change, in which case a match won't be made and a district won't be set for a rider.

I've found two examples of this in practice - Loughorough Students Cycling Club changed to Loughborough Students CC and there are riders for both Thornton Road Club and Thronton RC. The former changed their club name and the latter have someone with a negative rider id so I assume it was from the event with paper entries and someone has entered the club name that way.

The way around this is for you to pick up a fresh list of club names at the start of each run. That might be overkill, but then again for any newly registered clubs I guess you would need to pick them up too? Then you should be assured that each club name in an event will match. If you add any revised names to the list rather than using them to replace the old club name then you should guarantee a match with the club name.

I will add a district_code column to the rider table shortly.

**Comment by drnickw** [comment]
I`m not sure if it makes a difference where the match is done. AFAICS at some point we have to reference the text field given to us by CTT as a club name entered for a ride, with a club name in the list of club names within each district and sometimes they wont match. I get the keeping old club names bit and thats easy. Matching less so, although I guess if Thornton RC isnt in the CTT list then its likely it will be Thornton Road Club, but would you match with Thornton CC for example. I`m not sure how treacherous these matches are. I was hoping to avoid passing a column which is easy to derive with a look up table but if its easier for me to match than you then no problem.

**Comment by rogernclarke** [comment]
district_code column added to riders table. I have set it up with referential integrity to the district code table. This might give you a problem with any club you can't match to a district. What we could do to handle those cases is to create a row in the districts table with a code like "ZZ" and description of "Unknown" and maybe you could set not-matched clubs to district code ZZ. That would allow us to easily see where that has happened as well.

**Comment by drnickw** [comment]
Done for now but I`ll need to refine the matching for clubs not listed.

**Comment by rogernclarke** [comment]
Looks good. Have put the filter in place on rankings and riders screens.

Just one issue I know of... search for unknown district (blank) on rankings screen returns different results from the exact same query on the riders screen. I have no idea why! Any ideas?

**Comment by drnickw** [comment]
I`m sending a blank if its blank, not a code for blank. Is that right?
Otherwise no idea. Its only sent once (in the riders DB)

**Comment by drnickw** [comment]
I can do the ZZ thing if it helps. At the moment non matching and blank clubs will all translate to blank districts.
I`m not sure if I can match non matched clubs manually. Would be a bit of guesswork tbh.

**Comment by rogernclarke** [comment]
I think it would be worth trying ZZ. I've added a ZZ district code to the districts table so it should accept that value for a rider.
