### ISSUE TITLE
Indicate events that can't be ranked

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#27]
On event page indicate if the rides could not be ranked and link to FAQ.

For a ride that can't be ranked (on a rider's list of rides) also indicate if a ride could not be ranked.

Currently I have the rides table ranking_points column set as not null. What are you putting in that column for a ride that can't be ranked? Do you know of an example event that couldn't be ranked?

**Comment by drnickw** [comment]
I`m currently only passing you ranked events i think.
Loads of stuff gets filtered out along the way HC,TTT,tandem,tricycle,short entry events.
Need to have a think about what we want to show. 
If we want all single rider non HCs I can pass results an just leave score at 0,null, NA or negative, so you`ll know its non counting.

**Comment by rogernclarke** [comment]
Please set the unscored rides to have ranking points set to null. I've updated the database to allow the ranking points column to accept null values.

**Comment by drnickw** [comment]
See age = set to 0 instead

**Comment by rogernclarke** [comment]
Ok, I'll leave this assigned to me. I have a feeling I haven't taken this into account with which rides to display on the rankings list.

**Comment by rogernclarke** [comment]
Second question on non-counting rides - is it clear enough to just leave non-counting rides on the ranking list with the strikethrough? I think with points set to zero it is fairly clear and users can always click on the event link where they will see the message that the event couldn't have points awarded and why.

**Comment by rogernclarke** [comment]
Sorted on point 1 -  now determining a non-ranking event as an event with no rides having >0 ranking points.
On the second point, exactly that. On reflection I think they do need to be shown as they are now, crossed out, whilst they are within the timeframe of rides being shown for the rider in order to show transparently which rides count and which don't. This issue is now complete then.
