### ISSUE TITLE
Display of rankings

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#28]
Realised that the point I am going to raise isn't actually covered by the existing issue on ranking rules, so have created a new issue for it...

I haven't thought this through yet, so please chip in with your thoughts.

When first displaying the ranking page it has to display the overall rank as we've only got room to display one table, so it has to be a ranking table containing the overall rank (male and female). Clearly the rank being displayed is a rider's overall rank, which is the one you are populating into the rider history table. So far so good.

We can have a filter option to filter by male or female. At that point, if female is selected, I think it should show the female rank (and likewise the male rank if male is selected) as the primary ranking for the table. Whoever the top female is must be shown as #1 and not #nnn. You haven't passed me that data but I can determine that from the database.

Should the filtered table also display each rider's overall rank, or is that irrelevant and too much information? Would a rider want to see their (and others in their gender) overall rank whilst viewing a filtered list?

The same question applies for any other filter - age category, club, etc.

Following on from this, we are building up a history for each rider that includes an overall rank stored each week. But we aren't building up a gender rank over time, or age category rank over time. I could write a SQL query that calculates this when a rider profile is viewed, but I don't know how fast the query would be as it would potentially be processing every row in the rider history table in order to do the calculation! I think I would have to try this out before we do our full initial load in case I need you to precalculate some more data for the rider history table load.

**Comment by drnickw** [comment]
The rank is dead easy to generate once you have the score. I just sort by score and then add a sequential integer column to it. 
You can do this for any filter and I cant see the benefit of keeping any of this information as there will be 101 different ways of filtering. I dont know if its so easy in a database environment, but its basically a line number on the table so this should be easy to show. 
Likewise we can generate this info historically by sorting each week's data and getting the filtered line number. This would be easy as an R function but again might not work so well in a database. 
I`m concerned we dont try to anticipate everything we might want and try and store it all if its possible to generate otherwise we`ll have to be so careful we dont leave un-updated (dated?) data behind.
If you are looking up a female rider is it easy to also sort the filtered table in the background to get her gender rank? ( and same for other appropriate filters)
I`d be dis-inclined to have M and F categories, just stick with the overall percentile categories.

I think we will need R processing within the website if we are going to fulfil its potential eventually.

**Comment by rogernclarke** [comment]
It is no problem to produce a rank based on the set of rider history records for the latest date, my problem would be retrospectively producing that weekly back in history on the fly when someone wants to view their history graph.

On balance I think we should store the overall rank and gender rank on every rider history record. I think the gender rank is going to be especially important for the women (and would even improve my ranking considerably!). I will rename the rank column to overall_rank and add a new column called gender_rank. Does it give you a problem if I rename the ranking_points column to score? That seems a more accurate description.

**Comment by rogernclarke** [comment]
I've thought of another little problem with the rankings (and provisional riders).

There are clearly good reasons for viewing rankings including and excluding provisional riders.

But shouldn't the ranking stored in a rider's history only include complete riders? Looking at the top of the rankings there are a number of provisional riders. It would look wrong to display the confirmed rankings list with the ranking position that includes provisional riders. I could recalculate the position for the rankings list, but then if a rider looked at their rider history graph they would the overall ranking positions instead.

I'm thinking we may need to store both in the rider history table. And the same for the gender ranking. Which would make 4 ranking positions per rider history record.

I can't think of a way around doing that.

**Comment by rogernclarke** [comment]
I think I prefer your first scenario whereby a provisional rider gets a provisional rank that is shared with a completed rider. That way we only need the overall rank on the rider history record (to hold completed rank if f or c status and provisional rank if p status). That should avoid a big jump on completing their ranking status. That works equally well for the gender ranking as well.

I have yet to decide how provisional riders will be indicated in the rankings list but thinking of having them greyed out in some way. Maybe as well as brackets around their rank number.

**Comment by rogernclarke** [comment]
I've run into another little issue with display of rides for a rider within the rankings list. I'd like to display all of a rider's rides that fall within their eligible timeframe for rides rather than just counting rides as I think we should show the fastest ride and any slowest rides within the timeframe that we have discounted.

Fine for P and C riders, but for F riders I need to work on 4 months before the latest calculation date. I thought that would be easy until I started to think about what happens over winter. When we do a run in February then no-one will be an F. Is that intentional?

Have you defined a time period for the off season during which events won't count? Xmas and New Year events for example I wouldn't think had any merit in earning ranking points. I think there is one event in early November this year.

**Comment by rogernclarke** [comment]
I'm going to raise a couple of questions based on viewing the women's rankings including provisional ranks.

The table looks a bit all over the place until we get weekly ranking calculations for everyone, however...

- Hayley Simmonds will still be provisionally ranked first. As she has a lower score than Alice Lethbridge I think she is correctly displayed ahead of her in the table.
- Rachael Elliott and Emma Lewis will I think be provisionally ranked 2 and 3 with lower scores than Anna Turvey, ranked 2nd. Based on score they should be shown above her in the table, but then the ranks will read 2P, 3P, 2 going down the table. It looks a bit odd.
- Rachael Elliott's score doesn't tally with her results in the last 12 months. I suspect it is just using her result from 15th Oct. Did you run the data processing it after 7th October but with a calculation date of 30th September?

**Comment by drnickw** [comment]
I would leave the P rankings as they are and not give 2p 3p but just put them in where they fit.
I wonder if it would be better to have the completed rider first and then the Ps with the same rank following but in order of their score. The scores would then not be in order but perhaps we could bracket the p scores - not sure if its better as it is though, looks OK to me.
However the mens does look funny as the top 4 are not in score order at all?
Cant remember off the top of my head how the dates will work. I used a run date of 8th Oct, the day i did it but I used the actual race day as the weekly update day for each race as clearly I dont have weekly intervals yet.
All should be revealed when I pass you the right data type for CRI.

**Comment by rogernclarke** [comment]
I think we probably can't see the wood for the trees here until we have a weekly rider history record for each rider. Provisional men 2, 3, 4 would all have been ranked 1 on the date of their most recent rider history record. Once everyone has a rider history record every week then they would not have a provisional rank of #1 - I would expect them all to have a provisional rank of #2 based on their scores. I could display them all as #2 ahead of Harry Tanfield and within themselves sorted in score order. I think that would sort things out. I've applied a sort order of rank then score. It looks a bit odd but we'll need weekly rider history records to make sense.

**Comment by drnickw** [comment]
I`ve done a run for 2017 and 2018 till August then done August and Sept weekly so there are 9 entries for rider hx.  Each week takes 2.5 - 3 mins so to do the year will be a big job and i`ll wait and do it when we are certain it will be a one off. The last week I`ve sorted the results by score (rounded) so if you have the same score you will have the same category and rank, I`ve also sorted them in FCP order, but for some reason that doesnt seem to have been preserved in the transfer to DB (see score 20). Loosing the decimals in the score is irrelevant I think and looks better to the observer. It was showing mulitple entries in the riders page but it looks like youve fixed that.

**Comment by rogernclarke** [comment]
Looking at top 10 men and top 10 women with provisionals, I don't understand why a provisional rider with a lower score than confirmed position 1 would get a provisional rank of 1. Shouldn't the three men provisionally 1st actually be provisionally 2nd?

Same for Katie Archibald and Emma Lewis in the women's.

I've commented on decimals and rounding on the other issue.

**Comment by rogernclarke** [comment]
Meant to say, it makes no difference what order you load records into mySQL as order can never be assumed when selecting data using SQL so I will always (try to) control the order I display things in!

**Comment by drnickw** [comment]
I dont know. If you are ahead on points of the rider we have fixed as 2nd should you be better than second? I can make Ps the same rank as the rider they outperformed so on the rankings page they will always come first for that rank and the counting riders will be at the back of that ranking group.

**Comment by rogernclarke** [comment]
Looking at the latest rankings, I'm not understanding why John Archibald has a provisional ranking of 1. He has a higher score than Marcin, so shouldn't he have a provisional ranking of 2?

And a separate question, all the riders ranked 8th - are they in tie-break order using your rider comparison? Are we going to show then as all 8th even if we can order them?

**Comment by drnickw** [comment]
I havent built in the comparison yet so the 8th paces will be resolved.
I`m not sure what to do with the positions for provisional riders.
I did it like this so the completed riders would head up their rank and
have a tail provisional riders on the same rank.
Would be valid also to give the provisional riders the rank of the rider
behind them. Just depends on your point of view.
John appears to have a rank of 1 because although he is behind Marcin hes
in front of the guy who gets a completed rank of 2.

**Comment by rogernclarke** [comment]
I think I would have two arguments on turning it the other way round from how it is at the moment...

1. If a provisional rider was to be confirmed on their current score then they would be given the ranking behind the rider with fewer points (e.g. John Archibald would be second). He would also be ahead of Chris Bartley.
2. The ordering in the table looks right as it stands, but the number doesn't make sense.

I can't remember what ordering I have put on the list as it stands but I can easily make it be rank order, then F/C riders before provisional riders, then in ascending score order to sort the provisional riders.

**Comment by drnickw** [comment]
Seems reasonable, I`ll change that too.

**Comment by rogernclarke** [comment]
Going to close this one - I've changed the ordering back to how I had it before - order by rank desc, then score asc, then status code asc. It didn't look right to have provisional riders trailing c/f riders on the same rank as their score clearly showed they should slot in above. I think it looks right now.

I think you might need an FAQ on how you have got different ranks for riders apparently tied on points in the top 20.
