### ISSUE TITLE
Rider data - missing club names

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#3]
Club name is missing from Riders table for some riders who have a club name against their latest event e.g. Adam Mumford (rider_id 12428)

**Comment by drnickw** [comment]
Ages since I considered this. I think I`ve assumed you are still in your last club unless we are told otherwise. 
Certainly Adam Mumford is fine. Yes, just checked the code. That is what happens now.

**Comment by rogernclarke** [comment]
There are 171 riders with rider_id > 0 and no club name.

Not necessarily a problem there, but take a look at event 17366 - lots of blank club names, but also lots of male riders with girls names...

**Comment by drnickw** [comment]
Sorted I think? Still missing club names but sexes are fine now.

**Comment by rogernclarke** [comment]
Looks fine to me
