### ISSUE TITLE
update age on day

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#31]
If a new result comes in and the age on day is zero, do you want the db aod updated to zero or kept at last known age. if kept age the updated date will suggest this is a current valid age but it may not be. I could pass last known age but in brackets or some other marker if its validity is not known. Clearly you wont be keeping historical ages for each event (although i am).

**Comment by rogernclarke** [comment]
I think it should be set to null. I've amended the column to allow null values

**Comment by rogernclarke** [comment]
To start with I was just going to display the age category (i.e. juvenile / junior / senior / veteran) that you populate into the riders table. But you are also populating an age on the riders table which I'm intending to use for something like V40 / V45 etc. I'll leave you to work out the best age you can and update it on the riders table each time a rider has a new result. It is always going to be the last known age so will gradually get out of date if someone stops competing.

**Comment by drnickw** [comment]
You won’t have any age history will you? If I set age to null then you’ll be in a position of having lost a close/true age for no age at all. That’s why I was wondering if its better to show an age flagged as restricted rather than lose the data altogether.

**Comment by drnickw** [comment]
Sorry, just realised you do have age_on_day on the rides as well as riders db. Not a problem!

**Comment by rogernclarke** [comment]
Strange as the field should allow nulls. Think you will have to go with zero as it is an integer field...

**Comment by drnickw** [comment]
Its not the DB, i think its the way R handles setting variables to NULL. I may be able to resolve. Are you OK with 0?

**Comment by rogernclarke** [comment]
I was contemplating whether this could be closed or not...

Most of the riders with an age of 0 on the riders table have negative numbers, so no surprises there.

But why would someone like Richard Gildea (rider_id 34) have an age of zero? He has one ride record with an age of zero, but that isn't the most recent ride. (Just thinking he is a high profile TTF member!)

**Comment by rogernclarke** [comment]
It isn't that we display age per se but that his age-gender category just shows as Male instead of Senior Male

**Comment by drnickw** [comment]
Ok, I should be able to fix that. i`ll need some code to look at the last
age and date and check that he couldnt have gone beyond another age
boundary since that event.
I`m thinking my estimated birth day may be the way ahead long term.
