### ISSUE TITLE
Improved riders

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#33]
I was just contemplating what constitutes an improvement for a rider.

Is it that the points for their ride are lower than their ranking score? So if I have a score of 3,000 and get 2,900 for my ride, my score should go down as a result and therefore I have improved? If I get 3,100 points then my score may or may not change, but it is still a below par ride?

Should we be looking to indicate if a ride is above or below par for a rider based on their form? I was thinking along the lines of an up or down arrow next to the points for each ride.

**Comment by rogernclarke** [comment]
And following on from that, if I was to produce a list of most improved riders each week should it be the biggest reduction in score, biggest change in category, or biggest change in rank? Taking into consideration only C and F status riders?

**Comment by drnickw** [comment]
As said in email. I like the up/down arrow idea.
I worry that short term improvements (weekly) will pick up the anomalies in the data, and highlight the shortcomings of the system we are using. 
As said before I think a graph of score/rank/cat over time for each rider would be great.
For the homepage if we wanted a trending riders table i think we`d need it to include so many races over a time period to be valid (deliberately not specified just now!). Score or rank should be equally good as they track each other closely. Would you include Provisionals - may be too variable but we may pick up the next Marcin? 
Cat probably moves too slowly but perhaps a Cat improvement over 6 or 12 months would be one valid indicator.

**Comment by rogernclarke** [comment]
If I add a column to the rides table for a boolean improved_ride_ind can you populate it for every ride, set to true if ranking points < rider's score before race? I could then add it to event result sheets and we can see if it looks ok to keep? We can have discussion later about other ways to flag improvements - I'm keen with this specific one that you do the calculation per ride as the processing would be heavy at view time.

**Comment by drnickw** [comment]
I can do this fine. Go ahead and add column

**Comment by rogernclarke** [comment]
I've added the column improved_ride_ind to the rides table. It is a boolean so should accept 0 or 1.

Have also added a column called hits to the events table and will add one of the same name to the riders table so I can record the number of hits on rider and event pages when we go live. I would have added that column now but the model / database sync looks like it is going to wipe the data in a couple of columns so I'll hold off doing that until tomorrow. It is mandatory but defaults to zero so you shouldn't need to populate it when adding an event.

**Comment by drnickw** [comment]
I`ve done the processing for the improved ride ind but with an enhancement. I can pass you an integer (positive or negative) which is the number of places the rider gained (or lost) on where they should have finished according to their pre race rank. Clearly set to 0 for new (non ranked riders) who are taken into account (and also would be 0 if you finish in your expected position). It is possible I suspect, that they could have improved their score on the day but still not improved their position, so its not quite the same thing, but I think its a very interesting metric. I can pass you both if you want.

**Comment by rogernclarke** [comment]
Try just passing your suggested values into the column I have set up - I think it will accept -1, 0, 1. Let me know if it doesn't.

**Comment by rogernclarke** [comment]
I've just seen that the data is in the rides table so will assign this one to me now for the display

**Comment by rogernclarke** [comment]
Improved ride icons now displaying on rider and event screens. Take a look and see what you think. I have already seen some oddities...

**Comment by rogernclarke** [comment]
Two things that jumped out...
- Shouldn't every rider's first ride be a circle (zero)? Wasn't sure if for first rides in 2017 it was because you had used the rider's score for the whole of 2017 to get a starting point to then run your rankings.
- Take a look at Alice Lethbridge - a ride scoring 601 on 8th Sept has a down arrow and a ride scoring 1191 on 9th September has an up arrow.

More than happy to try your other suggestion. Just let me know what values you are going to send through.

**Comment by drnickw** [comment]
Checking thru there do seem to be some anomalies - i`ll recheck the code!

**Comment by rogernclarke** [comment]
Looking at the improved score indicator on the riders screen it looks really good - my rides tie in exactly with how I think they went, and looking at a few other riders it all seems to make sense as well.

I'll add an extra column to the event results so we can see improved score side by side with predicted position difference.

**Comment by rogernclarke** [comment]
On Point 1 - there are still a lot of first time rides which aren't a circle. Should we hard code all first time rides to be a circle?
On Point 2 - now displaying predicted position result on the event screen (temporarily in a column next to the improved ride so you can see the difference between them). Happy to go with the predicted position difference, but I think it should be displayed after the position (still within the position column). However, I was expecting you to load the predicted position for each rider and not the difference. I was thinking that at some point in the future you would load predicted positions in advance, so was setting up the column for that so I could do the comparison between actual position and prediction at run time - I thought that would save a database change at a later date. Can you send me that instead? I'm assuming that the predicted position changes when you get the results in to discount non-finishers?

**Comment by rogernclarke** [comment]
I've now coded for Point 3 as well - if you look at the rankings list you'll see I've put Simon Wilson in as moving up 2 places. I've decided to only show change in rank for C and F riders, not for provisionals.

**Comment by drnickw** [comment]
Hi Roger,
Point 1 - I need to check but I think I know why this is happening. should be an easy fix.
Point 2 - The prediction is complicated by what happens in the race (not surprisingly). I can predict if I have any valid ranking but as new and lapsed riders enter I cannot predict their positions. As such the data I have given is how many places they gained/lost from where they should have finished if only ranked riders rode, and then I`ve fitted the non ranked in, on the assumption they finished in their expected positions and not affected the rider in question. I`m not sure I can reliably get an actual position from this. If I took the prediction change from their actual position we would get a notional "predicted position" but as the results show non ranked riders there may be clashed as the ranked results got spaced out with non rankers. In essence our variable cannot show true "predicted position" as we dont know at the start everyones form. What it can show with authority is how many riders you beat who you wernt predicted to beat (or VV). I still think this is arguably the most important variable for assessing your performance on the day (its waht I`m most interested in when Adam rides). Not sure where we go with it when we are comparing "pre" predictions with results. I`d have to advise on the predictions page before the race the riders who dont have a rank and warn that they will affect the actual result. Although we are interested in prediction vs actuality to verify the program most people will be more interested in who they beat that wasnt expected (which is what we`ll give them). I agree that it will be easy to say you were predicted to come say 27th and ended up 31st and be disappointed but you may have performed well and beaten several higher ranked riders but had lots of non rankers finish above you. My variable will confirm your performance.
3 - Change in rank is running as I type. Will probably show all the changes on the db in the next 24 hrs. I`ll let you know. I`ve only included for C and F so others will be zero.

**Comment by drnickw** [comment]
Point 1. Unless you`ve seen otherwise, this only affects rides before 1.7.17.
This is because I`ve used a primer ranking file, derived from old data to serve as the ranking file for the first 6 months, just to get thinks moving. on 1.7.17 I no longer allow scores from this to influence the algorithm. From that date if you are P1 you will have a score change of zero. Before that date the score change will be based on scores derived from pre spindata data. I`m OK to reset all P1 to zero if you prefer, but we are actually using these notional scores in the first 6 months.
Have you seen any after 1.7.17 ?

**Comment by rogernclarke** [comment]
Here's a query for you on point 2 - how can Alice Lethbridge in the National 50 finish 3rd but have a position vs prediction of -24? There are several riders in that event where the rider finishes in a position with a lower number than their negative position vs predicted.

**Comment by rogernclarke** [comment]
I found the same issue on the women's national 10 and 25 so I think you are right about where the error is coming from.

predicted_position column now renamed to position_variance

Data in that field all now zeros as column was dropped when it was renamed

**Comment by drnickw** [comment]
I know how to fix it, just need to get a chance.
I`m really keen to get all the changes sorted before i do another run as
its taking 50 mins to do the Aug to Oct run now.
As far as I know this is the only thing outstanding although you wont have
seen the changes in the DB yet.
I`ll do a total reload again this time as need to change riders names too
(for initial)
Hopefully will be sorted in next 24-48 hrs.

**Comment by rogernclarke** [comment]
No rush, none of this holds me up at all with anything

**Comment by drnickw** [comment]
Have you got a plan for the opters out? I`m sure we`ll get some emails the
day we go live with requests to take their data down. Sorry this comment is
in the wrong thread!

**Comment by rogernclarke** [comment]
Think we can close this one now - any bugs found to be raised as separate issues
