### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#37]
I`m passing you the distance as "nn miles". The 10s 25s 50s and hundreds appear but the others dont. 
I`m pretty sure the last run had the other distances on too. Not sure why they dont show.
Possibly I need to pass just the number not the "nn miles" but strange it works for standard distances or is this just a throwback.
Maybe I`ll change to integer and try again.

**Comment by rogernclarke** [comment]
The distance is an integer so not sure how anything containing text would ever have loaded.

**Comment by drnickw** [comment]
Now is an integer and appears on website

**Comment by rogernclarke** [comment]
Looks good
