### ISSUE TITLE
Rider data - missing age categories

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#4]
Club name is missing from Riders table for some riders who have an age category against their latest event e.g. Adam Robinson (rider_id 1965)

**Comment by drnickw** [comment]
I left the cat blank if they were 19 or 23 as I cant be sure if they are junior/espoir or espoir/senior.
I`ve done the best I can with this now, If they have other races in the same year with a confirmed category I`ve assigned that. If not they are assigned JE or ES.
However I cant seem to update the DB. It wont let me overwrite the riders entries - something to do with the key. Are there constraints on this? Error : cannot-delete-or-update-a-parent-row-a-foreign-key-constraint-fails

**Comment by rogernclarke** [comment]
Ah, this is where the html shows a category but the csv only has the age, so the CTT event results show Senior but we only know he is aged 23.
Can you send me the SQL command you are using to write to the table?

**Comment by drnickw** [comment]
Its more complicated than that. If there is a category on HTML and the age is 19 or 23 I get the category but sometimes there isnt a category anywhere. Then I have to see if they have another event that year which does have a category so i can use that. If not then I assign JE or ES. We`ll need to monitor these as over time new results may shed more light but I dont want to just guess a category and be wrong so thought it better to show the ambiguity.
I`m at work but will forward the code tonight for the DBwrite.  There are options but I`ve tried "overwrite = TRUE" and this doesnt help.

**Comment by rogernclarke** [comment]
Ok - but in the case of Adam Robinson his result in the Rossendale event shows him as senior in the html so shouldn't that have been picked up then?
The mySQL error is because the Rides table rows for the rider being updated rely on the existence of the rider record for the rider_id. Not sure if there is a way for your database write to update rows without trying to update the rider_id but insert including the rider_id. My guess is that the database doesn't like any attempt to update the rider_id even if it is being updated with the same value.

**Comment by drnickw** [comment]
WRT Adam Robinson - yes, that is what happens now but as I havent overwritten the DB since the very first push none of the new features will be reflected in the (old) data.
I`ll look into updating the record without replacing the rider_id

**Comment by drnickw** [comment]
I`m sure this is spot on now. I`m adding ages for riders based on their predicted DOB range from the data we have and adding age cats based on the flow of their events over time. Have you seen any problems recently?

**Comment by rogernclarke** [comment]
All looks fine now, so closing
