### ISSUE TITLE
Display of riders with first initial

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#43]
Try to display the riders with only a first initial instead of a first name after those with a first name starting with the same letter

**Comment by rogernclarke** [comment]
I've worked out how to do this, but I need a full stop placed after the first initial please. The code is in place so when loaded with full stops you should see it fixed.

**Comment by drnickw** [comment]
Done?

**Comment by rogernclarke** [comment]
Yes, all fixed
