### ISSUE TITLE
Styling for Rider profile screen

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#45]
Add additional data and style the screen above the list of rides.

**Comment by rogernclarke** [comment]
I've styled the rider profile screen now and I think it looks quite good for the minimum set of data being displayed.

Worth checking out riders with the different category letters and ranking statuses.

How much additional information and what information do we need to add to this screen in order to go live?

**Comment by drnickw** [comment]
I think the screen looks very neat and streamlined. The enhancements for me would be best standard times and chart of progress over time. Most of the data is already on the page however. Not sure if its worth waiting for best standards if you`re keen to go live and I know the chart will need more exploration. Can you think of anything else worth displaying?

**Comment by rogernclarke** [comment]
For me I would add age-gender category ranking to the right hand side.

There are a stack of other things we could choose to show. I'm interested in doing vets standards. Also things like highest category reached (current season and LTS).

I wonder if we should move away from standard times a bit - personally I like them but maybe TTing has to change to stop the chasing of fast courses. We've got a system that could determine who is best without someone ever having to ride a fast course.

The problem I have with this screen is that whatever I add has to work for all screen sizes. It would be easy to put something together to display a stack of information that looks good on a desktop / laptop but just doesn't work on a tablet or mobile. This is going to take some thinking through.

What I'll do is see where we are at by Monday and if there is something quick I can do I'll add it, otherwise close this issue and we can work on new things afterwards.

**Comment by rogernclarke** [comment]
This is complete for release 1 - new features will have their own issues raised
