### ISSUE TITLE
Rider count for events

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#47]
Apologies if this is explained by something we have already been through...

I noticed the count for the number of riders I show on the event page doesn't always match the number of placings in the event. E.g. Women's national 50, count of 37 riders, list shows down to 38th place. 9th placed rider is missing.

Emily Meakin is shown in the results on the PDF and CSV but we don't have any record of her in the riders table (id 23059). She has placed top 10 in 4 nationals this year, but would only be provisional status.

**Comment by drnickw** [comment]
Tracked it down.
Shes only got 3 rides before my last run on the website.
Her first ever ride was early August.
Currently my final program doesnt run weekly till events after 1st Aug so I
input a ranking file from 31 July.
For this reason she doesnt have an entry in the ranking file when the
weekly program runs.
This program is the one which is updating the whole DB, not adding rankings
from new results.
When we are live I will be running the program which scores new races and
ranks them and then subsequently the one which goes through all the riders.
For this reason there should never be a rider in the entry file to this
progam who doesnt have a ranking listing.
ie, its an anomaly of the way I`ve cut into the year and wont be an issue
once we go live so long as I always run the weekly program after processing
all the new races (which I will)
Good spot though and had me worried for a moment but all the data is in the
files up to the point of the weekly program.
 I`ll just have to be sure this dosnt happen when I do the whole year
weekly to set up 2018.

**Comment by rogernclarke** [comment]
Good answer - fits with what I am seeing so will close this down.
