### ISSUE TITLE
Rider History - Populate table

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#5]
The Rider History table should contain one row for each rider for each occasion the rankings are recalculated, even if the rider has no new results themselves (and potentially if there is also no change to their rank). This will allow a history of ranking position over time to be built up for all riders.

**Comment by drnickw** [comment]
I was going to update the rankings after every race so they are as accurate as possible for the ranking generator graph. This would create hundreds of rider history entries. Maybe better to update the rider history only after they have been in an event but to have a current updated ranking position for everyone in a separate current ranking DB?

**Comment by rogernclarke** [comment]
Or maybe there is a position somewhere in between those two.
I'm thinking that it is quite rare for any one rider to race twice in one day, so there wouldn't be much point in updating the rankings more often than once per day?
I get that a rider's ranking points won't change unless they race (or until results start dropping off the date range used for ranking), but their overall position in the rankings will change every time someone jumps over them.
Are we in any case looking at processing results only once per week to make sure that we have the results in as far as possible to process in the correct order. In which case updating ride history once per week when the whole process runs would make sense. Racing is only for about 8 months of the year so about 35 weeks - so 35 rows per active rider per year gives 200k - 300k rows per year I think. The table only holds three integers and a timestamp so each row is quite small (and I think I might be able to make the integer columns smaller).
Would that work for your side of things?

**Comment by drnickw** [comment]
I was processing the rides en mass and then adding the rider history afterwards. The current system I`m processing en mass till 1.8.18 and then doing weekly runs which include updating for each event and then adding the updated rankings. I`ve been basing it on Wednesdays. I guess this will be effective once we go live. I`ll wait till the Wednesday before the 1st Feb to do a new ranking and then run weekly. I`ll just use everything new each week and if things come in late they will go into the next week. Once Startsheets are up and running we can drag them in in the same way every Wednesday for the coming weekend (or more advanced if available). I reckon I can get the whole weeks processing done in 10 mins although its always worth casting and eye on the file which comes in from the CTT website to look for anomalies. I`m sure I could set it up for you to run if I was away - I`ve already started setting up a process  which calls all the programs in turn and passes the files between them so could end up just being a 1 button run.

**Comment by rogernclarke** [comment]
Does that mean we won't have rider_history records before 1/8/18 if the processing is en masse until then?

Why would you run a re-processing just before the first race of the year? To drop everyone from an F back to a C to give a level playing field?

**Comment by drnickw** [comment]
Yes it would. I can run it for both years if you want, now I`ve got the run
time down a bit. Or maybe you`d be faster - I`m running on i5 2500K 3.3Ghz
4GB ram at < 2 mins a week.
The data will be a bit hitty miss in the first few weeks of 2017 as the
Primeranking file is nowhere near as good as our data but its better than
nothing. That would give us full rider history.
I would plan to rank in late Jan otherwise people may have really good
rides but their scores/ranks could be going backwards as the last run was
end of season. This way we reset everyone for the new year wrt LPCF.

**Comment by rogernclarke** [comment]
I'm on an i3 but with 6gb, so no idea which would be quicker!
I think the full history might be worthwhile for 2018, not sure about for 2017.
January reset i think would only change F to C - L and P wouldn't be affected?

**Comment by drnickw** [comment]
I`m sure there wont be much in it. I`ll keep it here!

I guess as were not counting rides from Nov to Jan inc then there wont be
any rides dropping off in this timespan from the year before.
Its easy to do and will start the year off on an even keel.Any downside?

**Comment by rogernclarke** [comment]
No downside I can think of. Most riders won't race in the first week of the year anyway, but as you say it does give a clean start point for the year.

I guess we can close this one then?
