### ISSUE TITLE
Ranking table jump

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#50]
Is there a way to jump to a page in the rankings.
I would imagine you might want to see riders who have rankings close to yours. 
You can search on your name and get your rank.
Would it be possible to contextualize this by showing you highlighted in the middle of a page with the 10 riders above and below you, or maybe the ability to jump to a rank number rather than trying to page through starting from the beginning.

**Comment by rogernclarke** [comment]
This isn't easy.

To make that work you'd have to do a rider search which only returns the rider you are interested in. So effectively that would mean you want to put this on a rider's profile page.

I was thinking maybe to display riders in the same category - category search in rankings list?

Or would riders other than in the top 100 be more interested in those in their district just above and below them? Or for districts other than ours potentially by selecting more than one district.

I'll keep this open but move to release 2.

**Comment by drnickw** [comment]
If you know you are ranked 4000 is there a way to advance to the 4000 th position in rankings?
The only way i can see to do it is to increase the page size to say 1000 and then page and scroll.
Otherwise you have to page through hundreds of pages of 20.

**Comment by rogernclarke** [comment]
The only other way as it stands is to change the number in the url to jump n number of pages at whatever page size you have set.

I was surprised that the standard pagination doesn't have options at each end to jump up/down by 10/100 pages.

How often would any riders actually want to do this? It hadn't really occurred to me to look at my record that way as I wouldn't expect I would know any of the riders on the same page, so it wouldn't seem very relevant. That may be different once you are in the top 100 or so and are more focused on national rank and not against local riders.

Again, maybe best to initiate this from a rider-profile page - button called something like "show rider in rankings list" to open rankings list at appropriate page?

**Comment by drnickw** [comment]
I’ve always thought this was a problem with websites. I didn’t realise it was in the fundamental design.
If you can’t easily scroll through the rankings I guess the overall is largely irrelevant to most people although as you say the filters make sense. If you just want see yourself you can get your rank from the riders page.

**Comment by drnickw** [comment]
Looking at Adam Jarps results they look counter intuitive. his last event was good but he lost several categories. This is because he went from being F to C between his penultimate and last events. Its hard to work this out, especially if you dont know the system. I checked on my files to see what had happened. I dont think we actually say anywhere on the website about completed and frequent (except in the FAQ) and you cant even tell easily in the counting rides (although you can see what is dragging him down). Its not too hard to find for AJ as he comes close to the top of the junior ranking table but how could someone in the 4000s easily check their counting rides? Maybe we need to be more explicit about some of this or people will think it just doesnt make sense.

**Comment by drnickw** [comment]
Thinking about this, how about having the counting rides button on the rider page too, or even highlighting the points for the counting rides in a different colour. 
Do you have access to the LPCF codes? - maybe we should display the rider status on their page too.

**Comment by rogernclarke** [comment]
I currently display the rider status if they are F or P. We can display a C or L but I started off thinking that C would be the norm and wasn't sure how descriptive Complete is.

Agree with highlighting the counting rides on the rider screen, would just have to think about the best way to do it. Needs to work for anyone who might be colour blind. I'll have a think.

**Comment by drnickw** [comment]
I agree complete isnt the most elegant expressor. The only other word I can
think of is qualified.
I guess in AJs case unless you considered that his status had changed you
may not realise this just because it showed him as complete as it wouldnt
highlight that he had been frequent before.
It may be worth showing riders as "lapsed" on the RHS just to be clear its
not just something wrong with the presentation?

**Comment by rogernclarke** [comment]
Ok, I've added lapsed status to the set of statuses that display - should I add Qualified as well?

Is the only other thing to do on this issue to indicate the counting rides on the rider's screen?

**Comment by rogernclarke** [comment]
I've changed the styles for counting / non-counting rides on both teh rankings list and the rider screen. Let me know what you think

**Comment by drnickw** [comment]
It looks like you`ve crossed everything out apart from the counting rides?
I think thats too much of a focus on them. I get that you can still see the other rides but I think one of the strengths of our system is that is shows so much info all in one place and a lot of people will be looking on the website without a particular interest in the counting rides.
I could see some justification for crossing out all but the counting ride points, but even then I think you yourself really like to consider points for each ride whether or not they are counting to see wha tit all means. I`d rather highlight the counting than suppress the others.
I know you were concerned about just changing the colour due to people with colour blindness, although there must be precious few of them. If not that then how about some kind of block colour behind the number for the counting rides so even if you cant see what colour it is you can see its there?

**Comment by rogernclarke** [comment]
I should have said to clear your browser cache - my changes removed all strike-throughs from both lists, with counting rides now being bold, and text colour for non-counting rides now being grey (so as you say highlighting the counting rides). I need to see if there is anything I can do to force the browser cache to refresh when we do release 1.1.
I believe that 8% of men have colour blindness, so not an insignificant number.

**Comment by drnickw** [comment]
Spot on.

The cache does seem to be causing problems. If our format changes dont
transfer to users without them having to tinker under the hood I think
we`ll loose some enthusiasm.
I presume there is a way of doing this?
It didnt seem to be a problem before we started with dev?

**Comment by rogernclarke** [comment]
It isn't just related to DEV - it was the same before, just that you didn't know when I made styling changes to know you weren't looking at the latest styling! Sometimes you don't need to refresh and it picks up the new file. All yesterday evening my browser picked up the new file every time I made a change.
I'll read up on it. The obvious thing to do is change the name of the CSS file and then the browser will have to download the new file as it won't have a copy of the file with the new name.
Is this issue ok to be closed now or do you want to keep it open?

**Comment by drnickw** [comment]
The post seems to have been hijacked along the way.
The original did consider other ways to access the rankings eg more than 1 district, or possibly being able to zoom into the rankings at a certain point.
I still think this has some relevance.
Also may be worth keeping s thread open on the cache till it’s resolved.
The counting rides look fine now and a definite inmpoveemnt making them more accessible.
We’ll need to do some more FAQs on s before we publish.
Did you add lapsed and qualified to the status bar?
I’ll try and run both years later today to get the full rider hx sorted.

**Comment by rogernclarke** [comment]
New issues opened for CSS and FAQs.
We may need to create new issues for what this thread was originally about!
All statuses are now shown in tag on rider screen.

**Comment by drnickw** [comment]
Cant see lapsed on the screen (Shona Bennett) ?

**Comment by rogernclarke** [comment]
I'm onto it - did we decide that we would display the category for provisional riders on the rider profile screen? I can't remember. As it stands we aren't.

**Comment by drnickw** [comment]
It would be out of date as once someone has lapsed we stop creating rider
history for them.
If we did it would have to be stated as "last confirmed category".
however this should be evident now from their event results.

**Comment by rogernclarke** [comment]
For lapsed, yes, but what about the provisional status riders? We show it on their event results, so should we show it at the top of the screen as well?

**Comment by drnickw** [comment]
Yes, i thought we did. Sorry, I should have read the email properly.
Fitting emails in between patients!

**Comment by drnickw** [comment]
Back to the original question, I’m often looking at riders and wondering what their score is currently. Currently the only way to tell is to go into rankings and enter their name?
Reading back through this posting I know the ranksort idea is better from the riders page. That’s usually easy to access as you just click on the rider, but in my laziness I resent having to type the riders names into rankings!
I was thinking at first about having score on the rider page too, but I wonder if the ordered rankings on the right top of the riders screen could be hyperlinked to go into the respective rankings at the point where this rider resides, so I can see my rivals in various categories and have quick access to the score from there?

**Comment by rogernclarke** [comment]
I like that idea. I should be able to set the start point of the list based on the rank, and the filters based on which link they click on. Should work well.
I think maybe we should also display the score on the rider page.
