### ISSUE TITLE
Stable position for new riders

### ISSUE THREAD

**Issue by drnickw** [rogernclarke/Rankings#53]
The black spot on the position either indicates the rider hasnt moved position or is a previously unranked rider. Could we have a different symbol for previously unranked? maybe an unfilled spot. Can you distinguish this. I can pass you info but the field currently uses negs zero and pos so i cant easily put a code in for this.

**Comment by rogernclarke** [comment]
Could also use a left hand arrow for someone who has matched their predication, and a spot for new riders - that might be more intuitive than a spot vs circle.
So I effectively need to determine if a rider was either never ranked before the event or was an L at the time of the event?

**Comment by drnickw** [comment]
Yes, or if you change the field I could pass you something like 0.5 for a new rider as everything else would be an integer. The dot is stable for the score and rank isn’t it. Need to keep to the same thing for all the tables. Maybe the horizontal arrow for them too then.

**Comment by rogernclarke** [comment]
I'm tending towards adding a new column to the rides table called ranked_rider_ind set to true for a rider with a ranking (P/C/F) on the day of the event, otherwise false. Minimal storage and keeps things clean.

That would make it easy for me on the event results.

What about on the rankings list? I'm going to need to distinguish a P1 from any other sort of status - and we didn't bring the numeric part of the ranking status across... Maybe we need to revise that decision

**Comment by rogernclarke** [comment]
Actually, it isn't a P1 I need to identify - it is a C6 who was a P5 on their previous rider_history record I think.

**Comment by drnickw** [comment]
I already have a valid_rider column for PCF so that should be easy.
I can also flag at P5-C6 if you like.

**Comment by rogernclarke** [comment]
I've added a column called ranked_rider_ind to the rides table as a boolean, to be set to true if a rider had a ranking on the day of the race, and a column called newly_complete_ind to the rider_history table to be set to true if the rider's ranking status changed from P to C since the previous rider history record.

**Comment by drnickw** [comment]
Just been thinking about this on my ride. I reckon we are re inventing the ranking status in triplicate.
Why dont i just put an "A" in ranking status for a new P from below and a "B" in ranking status for a new "C" from below. You can treat them just the same as P and C but they will give you the extra info you need.

**Comment by rogernclarke** [comment]
I see what you are saying, but...
I'm currently translating codes F and P into the full text for display in a couple of places - it wouldn't seem quite right to translate both A and P into Provisional. If we were to go down that route I'd prefer to have the first letter retained as it is and a suffix added with further meaning. Something like CN for newly complete. I could then chop the status up into its component parts. Happy to go with that for the rider_history but think we still need the ranked_rider_ind on the rides table.

**Comment by drnickw** [comment]
Tbh it doesn’t really matter to me what I send. I don’t need to keep these variables in my file as I can easily derive them and won’t reference them again. It just feels like we have started creating lots of additional columns to avoid any processing on the DB side. I understand why it’s hard to process too much from the dB but they seem to be getting a bit cluttered. The codes feel time specific and will become irrelevant as soon as they have been used and will apply to only a tiny handful of riders. I wouldn’t have any qualms about using 1 code to include and qualify another ie A meaning P and new P, I don’t see there being any conflict or ambiguityI. Not sure the codes equate to rides however, I think they are rider history. What if someone has 2 rides in the week.
However as said it’s easy for me to pass what you like so whatever suits is fine.

**Comment by drnickw** [comment]
Maybe you are right about rides - just trying to get my head round this. If I process rides currently the predictions are set at the start of that rides processing based on what rank info I have. This will not necessarily be the same as the pre weekend prediction if some riders have ridden another event in between. So the prediction will change before the race results come in. Currently this isn’t a problem as no one has seen the predictions in advance but it will become a problem once we pre predict. Also if we are using new predictions we should probably show this on the race results table so you will need predictions to be race specific not week specific.

**Comment by drnickw** [comment]
Ok, I’m happy to go with the indicators.
It has made me think about the in week re ranking however. If someone rides twice would you expect them to show the changes since the last week or since their last ride, wrt the race results, ie do I set both rides to new rider or just the first? Clearly the ranking will be C since last week not C since last ride.
I’m inclined to just set the first only, as the second ride does have the benefit of the results of the first and will be affected by it so denying this is not really the full story. We’ll just have to say when we produce the start sheets that they are provisional at the time and the full predictions won’t be available until just before the race (which as far as Spindata is concerned means after).

**Comment by rogernclarke** [comment]
Happy to go with your thoughts on that one

**Comment by drnickw** [comment]
Indicators now filled and looked OK to me last night but see you`ve been tweaking the site today and the position and rank change columns see to have gone! I`m sure they`ll be back. if you ride twice in a weeks processing your second ride will not be classed as new.

**Comment by rogernclarke** [comment]
Looks like I've properly broken the site now - may take a while to reinstate...

**Comment by rogernclarke** [comment]
Phew - thought I might have lost an indeterminate amount of code, but seem to have recovered it all!

My column name change dropped the overall_change_in_rank, so those all left arrows for now. Will check once reloaded.

**Comment by drnickw** [comment]
One for you I think.

Sent from my iPad

Begin forwarded message:

> From: Spindata ***@***.***>
> Date: 27 December 2021 at 20:53:19 GMT
> To: ***@***.***
> Subject: Spindata: Ranking list
> Reply-To: Tony Russell ***@***.***>
> 
> ﻿This is an enquiry email via https://www.spindata.co.uk/ from:
> Tony Russell ***@***.***>
> 
> Hi
> When i look at the ranking list, i have an option of selecting a different amount of 20 to view... but when i choose something different it always reverts back to 20...
> Known glitch?  Not an issue, just letting you in case you didn't :)
> Many thanks
> Tony
>
