### ISSUE TITLE
Ranking improvement by gender

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#55]
When displaying the overall rankings list the change in (overall) rank shows correctly.

When filtering the rankings list by gender it is the gender_rank that is displayed, not overall rank. We are currently displaying the change in overall rank next to the gender rank. That means that Alice Lethbridge shows as #1 but has moved down by one position since last week!

**Comment by drnickw** [comment]
I can pass you a column being gender rank change if you like.
Its easy and quick for me to do.
Cant help thinking this is not the way forward long term however. 
I dont want to pass a column for every possible filter!

**Comment by rogernclarke** [comment]
I think that is the only solution - we won't need any more as we only hold overall rank and gender rank, we don't have variance on anything else in the rider_history table.
I've amended the existing change_in_rank column to be called change_in_overall_rank and added change_in_gender_rank. Will be very quick to amend the code at my end once the data is there.

**Comment by drnickw** [comment]
Ok, although presumably if people filter ranking by district or age range
you will not show the rank change, only for overall and gender filters.
I`m sure I can get this column to you in the next few days.

**Comment by rogernclarke** [comment]
As it stands I was still going to show the rank (which rank depending on whether a gender filter is selected or not) along with the relevant change in rank indicator/number. If on looking at it we think it is confusing then we can hide it.

**Comment by rogernclarke** [comment]
I think I have this coded now so fingers crossed loading the data will make it show correctly.
