### ISSUE TITLE
Riders with an initial -again!

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#57]
No idea why but riders with only an initial have reappeared at the top of the riders page. Only 3 of them now, but still don't know why they have come back to the top - the original fix is still in place!

**Comment by drnickw** [comment]
Weird. I see they still have the punctuation.

**Comment by rogernclarke** [comment]
I haven't changed anything, but there are no longer riders with first initial at the top of the riders list!!

I'll close this quickly whilst it is working ;-)
