### ISSUE TITLE
Predicted results

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#61]
Display predicted result sheet for an event. Need more detail about what this might look like.

**Comment by drnickw** [comment]
Thinking a bit about this and how we can use the existing databases.
The rides db could work. If i was to use the predict column for the prediction and leave the position column blank it would be clear this event hadnt been scored/completed.
I can use the time column for the predicted time. If we want a slow and fast time prediction too then we would probably need new columns.
The riders table would need new riders which were in the startsheet entered in the DB presumably. Cant see a problem with this at all. 
Rider history wouldnt have an entry till the event was scored.
Events DB would just have a blank processed date until completed. May have a problem if events are cancelled after the startsheet goes out or they could be forever left as pending!

**Comment by rogernclarke** [comment]
The only bit you lost me on was the prediction column - is that a new column?
If we aren't going to keep the predicted position after we have the results (we have position variance) then I'd be inclined to use the position column for the predicted position. On the event screen we will know from the event processed date being blank that the event hasn't yet got results in; on the rider screen we can tell if there is no time or distance and therefore not to display the ride. I think.

**Comment by rogernclarke** [comment]
Ah, I forgot you were predicting time (or distance?) as well as position. Would it work if I allowed position variance to be null and a null position variance indicates it is a prediction? I'm just thinking of keeping it as close to the result sheet model as possible.

**Comment by rogernclarke** [comment]
I can't think I'd have a problem applying a percentage picked up from the course, so let's assume I can do that bit.

**Comment by rogernclarke** [comment]
Adding to release 1.2
So far it looks like we need new columns called predicted_time and predicted_position. Are you still wanting separate slow and fast predictions? Were those to be calculated on my side or stored?
Let me know what else needs to be added and I can get the dev database set up.

I will need to start looking at the design changes for the event screen.

**Comment by rogernclarke** [comment]
I've added three new columns on DEV:
bib - integer
predicted_time - time
predicted_position - integer
predicted columns allow null values

**Comment by rogernclarke** [comment]
I've added another new column called predicted_distance to the rides table. It is decimal(6,3) and defaults to null.

**Comment by rogernclarke** [comment]
I guess I should leave this open until duration event predictions are in hand?

**Comment by rogernclarke** [comment]
Moving this into release 1.6.1

Only remaining items are to reduce predictions to two decimal places and to high predicted order at finish tab for duration events

**Comment by rogernclarke** [comment]
These last couple of things are now complete on dev so closing this issue!
