### ISSUE TITLE
Include distance events in rankings

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#64]
Rate rides for 12 and 24 hour events

**Comment by rogernclarke** [comment]
I've coded this up now so loading the events into the database should hopefully be all that is needed now. I'll probably have to tweak column widths once I can see the data.

**Comment by rogernclarke** [comment]
Just a thought - for duration events can you also load the time into the time column for the ride? That would allow potential future stats such as a total time of racing to be shown on the rider page.

**Comment by drnickw** [comment]
Can do, obviously it will be 12 or 24 hrs, although this isnt really right
as clearly some people bail early and we wont know who or when.
I guess thats true of any event but if you enter a 24 and bail after 2 hrs
your total for the year will be erroneously overwhelmed by the one event.

**Comment by drnickw** [comment]
OK, must have been something funny about 17282 as several people didnt get
to 100 miles in 12 hrs.

**Comment by rogernclarke** [comment]
Looks like I have some tidying up to do on the 12 hour events pages...

**Comment by drnickw** [comment]
I`m just looking thru the website now.

I`m sure you are perfectly capable of spotting errors but heres a few i
picked up.
The events listing page shows the 24 hr as 24 miles in the distance column.
hardly surprising. Can you keep the column but just change the descriptor
from miles to hours.
The riders results page is showing latest rank not rank on the day. I`m
pretty sure I`ve put the right data in.
I`m still not clear on the cat tags. I find it hard to distinguish some
numbers, eg 5 and 6. Also I think the c d and e are all still a similar
hue. I dont know if you can find better colours - i get the problem wit the
white/black script.
Did you try lining them up? Its especially busy on the riders page as there
are so many variations in event name length.

Ranks look good on the riders top right and I think really interesting.

Is there anything else for 1.1 ?

**Comment by rogernclarke** [comment]
Ok, I think I have now got the duration events sorted out so if you spot anything specific to a duration event that doesn't look right now then let me know. If it is a column not wide enough then you may need to delete your cached files in your browser.

I know of one thing i still need to add, which is the event distance filter needs to have 12 and 24 hour events added, so we'll leave this issue open until I've done that.

Category tags are still half done - I was having trouble with the SQL so getting the current category to display was a stepping stone. Hoping I can finish that bit off fairly quickly.

I've still got a display issue to sort out with category tags in the lists. You'll see it on a PC as the rows being higher than they used to be, also with the category tags floating away from the rider names. I need to resolve those first, then we can look at how it looks if placed before the rider names.

We were also going to add display of placed riders above results list on event page as part of 1.1

I like my improved placing in the new rankings!

**Comment by drnickw** [comment]
I still seem to have points and distance overlaid. Not sure how i clear the
cache if thats the problem. I took the dev.spindata bit out as per
https://www.thewindowsclub.com/clear-cache-cookies-specific-website. It
doesnt seem to have changed.
Yes, you seemed to get a good result in the 12hr so it was worth processing
them.
I wonder about the order of the rankings in the top left.
Would it be better in descending order so overall then gender then category
then district. I appreciate the women may prefer their gender rank at the
top but I think it would flow better now there are more rankings.

**Comment by rogernclarke** [comment]
Yes, that is the browser cache thing you are seeing. if you are using chrome click on the three vertical dots at the top left, then settings, then advanced (at the bottom), then clear browsing data.
We can move the rankings around and see how that looks...

**Comment by drnickw** [comment]
The units are still wrong for the distance events on the events page as
discussed this morning.
If you enter "other" for distance and go to the bottom of page 2 you`ll see
this years 24.
It shows it as 24 miles in the distance column. I know distance has become
a misnomer as a column heading but I think if it said 24 hrs people would
accept that as the event "distance" as its a well recognised event
"distance"

**Comment by rogernclarke** [comment]
That is fixed now

**Comment by rogernclarke** [comment]
I've now added 12 and 24 hours into the distance filter on the events list page.

I think this issue is now complete. Feel free to close if you agree, or let me know if you spot something
