### ISSUE TITLE
Event with no results

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#68]
I've just stumbled on event 16146 which has no results. It is a Christmas 2017 event, so wouldn't have any ranking points, but I was expecting to see the results

**Comment by drnickw** [comment]
As discussed. I can push them but the scores for other rides are subtly changed so may be better to reload the DB.

**Comment by rogernclarke** [comment]
As we are about to do a full reload for 1.1 then let's just include them in that load. I'll close this one.
