### ISSUE TITLE
Display rider categories on rider results list

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#70]
Display rider's category on each result on results list on rider screen

**Comment by drnickw** [comment]
I have mixed views on the formatting. It seems a shame to space out the rides to 2 lines just to accommodate the flag. I can see it doesnt look right before the event being the wrong way round. I think on the rider pages its fine as most rider names are a similar length and I`m happy with that.
I did notice when it was on the first line and after the event name there were occasions the cat flag was bounced off the page altogether. Could it be to the extreme right of the event name field but still on the first line and in a vertical column.  
The advantage of the flag is really in seeing change over time, I dont think people are particularly interested in the specific number after a certain ride but rather how theyve changed over time, so an alternative would be some kind of horizontal chart showing change over time but i appreciate this may be much harder and perhaps we have an acceptable solution this side of release 2?
Your graph would look fantastic, Adams hasnt really changed that much over 2 years (although still positive).
Could the vertical R hand side work with a tiny deviation left or right for each category so showing a trend in an almost imperceptible way. I dont know how hard it would be to micro position the flag based on its value and I`m guessing it wouldnt work at all on a small screen.

**Comment by rogernclarke** [comment]
From your comments I'm wondering if you need to clear your browser cache again to pick up the latest version of the css file. At one point yesterday evening the tag was on a second line but it isn't now - the display is exactly as for the event results.

The way it is now set up will stop the tag ever getting shunted out of the column (that was one of the fixes I was working on). I don't display the tag at all below tablet screen size. Above that the event name gets truncated when it bumps into the tag when the tag hits the right hand side.

I can do what you've suggested with the tag and move it to be right aligned within the column. I could also use the numeric part of the category to change the alignment, but I suspect for most people the alignment would change very little and it might just look messy.

I'll leave it as it is for today so you can refresh your css file and see what it looks like now, then tomorrow I'll right align the tag so we can see what that looks like.

**Comment by drnickw** [comment]
yes, looks better now all on one line.
I agree there probably isnt enough change in cats for the floating position
to work.
would be interesting to see them right aligned but its ok as it is now.

**Comment by rogernclarke** [comment]
Tags are now right aligned on rider screen. I didn't think I'd like it but it looks alright. Clear your cache if you don't see it.
Do you want to see what the same thing would look like on the event results? It's dead easy to change

**Comment by rogernclarke** [comment]
I should have said, we need the 2017 history if we are going to show the category after each event.

**Comment by drnickw** [comment]
I like it. I think it looks neater and easier to see where it changes.
I`m happy to do a 2 year run at some stage when we are ready (it will take
> 2 hrs so i`m kind of hoping it will be a one off) .
Are there any other changes you forsee in the near future to the DB. (cf
recent comment on counting ride index and rider status and predictions)

**Comment by rogernclarke** [comment]
The only thing I can foresee is that for awards we might need to pre-calculate and store them. If we want to display on an event page who has placed top three in any of a number of categories that is probably going to be fine running SQL from what we have already stored at runtime. But if we want to do a similar display on a rider page (i.e. trophy cabinet sort of idea) then I'm not sure it is feasible to calculate across all the events they have ridden for all of the categories they might qualify for within a reasonable response time.

However, if i need this in a separate table I can populate it myself from the data already there so I wouldn't need you to run through all the data to work it out.

So no, I can't think of anything else.

**Comment by rogernclarke** [comment]
I think this is done
