### ISSUE TITLE
Display of event distances to handle two decimal places

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#85]
Check screens that display event distance - lists should not show decimal places but event screen should.

**Comment by rogernclarke** [comment]
I've set this up on dev so that no decimal places for event distance are shown on list but they are shown on the individual event page. If you go ahead and load the new event distance data to dev then we can check it all looks and works ok.

**Comment by drnickw** [comment]
Dev look good to me now.
See 2 MTT events.
And E14/28.
Seems it keeps decimals as needed on events listings and always adds .nn to
the individual events.

**Comment by rogernclarke** [comment]
Ah, that hasn't worked quite as intended... I hadn't meant to show any decimal places on the lists. I'll have to make that column wider if we show the decimal paces there. Are you ever going to use the second decimal place? (my fear is 100.25 miles!) I've now removed redundant zeros from the distance on the individual event screen.

**Comment by drnickw** [comment]
My files have accuracy to 0.05 as this does effect comparing courses for
how fast they are relative to one another.
If you want to round them to nearest 10th or integer for display I`m OK
with that.
Only risk is rounding a rounded number could flip it the wrong way, but its
a small error and will be right for processing and on the individual event
screen.
