### ISSUE TITLE
Trophy cabinet / awards

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#88]
Recognise achievements in an event in various categories as "awards". Awards to be displayed as a new tab on the event page (award / prize winners) and on the rider page (trophy cabinet).

Possible awards:
Male
Female
Vet on actual time by age category (M/F)
Vet on standard time (M/F)
Espoir (M/F)
Junior (M/F)
Juvenile (M?F)
Spindata category (A/B/C/D/E)
Fastest team of 3 (M&F or just mixed?)
Team (Bidlake) - fastest 3rd counter
Biggest beating of predicted time (handicap)

What about recognising PB or SB? Maybe in terms of best points score rather than best time.
Anything else?

**Comment by drnickw** [comment]
Let me know what data you need me to generate for this when you`ve decided on the exact awards. I assume some will be done on the website but some I`ll need to do.

**Comment by rogernclarke** [comment]
Will do.
I think what I need to know first is how your results load process works. Is it a single file with one record per ride (result) that you load in one upsert? (i.e. not one upsert per event)
I'm just trying to work out if there is an action on the database per event or only a single action that covers all the results. I may be able to do all the processing on my side in a similar way to the vets results. I think all I need to know is when to calculate the awards for an event and that trigger will need to come from you in some form.

**Comment by drnickw** [comment]
Yes, all the new rides are added in a single command BUT, there are now 2 scenarios. If the ride didn’t have a startsheet it just gets written in but if it did then a separate upsert changes the ride entry from the startsheet processing to add the results.

**Comment by rogernclarke** [comment]
I've written the processing to calculate the awards.
There is a new stored procedure on the dev database called populate_awards_for_event for which you pass in the event_id as a parameter.
There is another stored procedure called populate_awards which loops through events calling the other procedure. I still need to set up some logic in this procedure to decide exactly which events it needs to process.
All we need from the R processing is a final step after loading all data to execute the following MySQL command:
CALL populate_awards

I've decided we shouldn't have awards for fastest senior (they should be beating hte other age categories) or fastest A cat (they should be winning the event).

I've populated the data for 2018 and 2019 and there are 41960 awards across 6524 riders.

**Comment by drnickw** [comment]
sounds good.
is it running on dev now?
where do the awards appear?
i can trial the MySQL command as appropriate, let me know when to do it.
if its a sort of log book for riders achievements then shouldnt it include
A cats/seniors , or does it just exclude them if they dont win?

**Comment by rogernclarke** [comment]
This is just the data processing / data load of awards so not the presentation on the website as yet. Hoping to code some of that in the next week or so.
You can see the data in a new table called tt_awards.
The MySQL command is there for you to try whenever you want. It is currently set to calculate awards for all races in 2019, but I'll refine that before we go live so it will just process the events it needs to.
I'll do some analysis of how many top 3 A cats aren't in the top 3 of their race, and likewise for seniors. I don't think it will be many. I also think it will be meaningless for them - surely an A cat expects to beat B cats for a top 3 placing, and likewise for seniors?

**Comment by drnickw** [comment]
so they would get an award for winning or top 3 and therefore shouldnt get
one for being the first a cat/senior if this doesnt apply. seems logical.
I`ll have a look tonight. I cant log onto cpanel from work.
Cheers,
Nick

**Comment by rogernclarke** [comment]
I think this is complete on the events page now, but...
I've discovered a small issue with what we are doing with missing club names on some events, and having looked into it a little bit I'm not clear how you are currently handling missing club names.

There are 6 events in 2019 so far where there are some riders with missing club names. The best guess is that these events either had no start sheet published on the CTT website or the riders in question weren't on the start sheet that was published.

It looks like for these events the results are uploaded and for some riders the name links to a rider id and for some it doesn't. It looks like those linked to a rider id have a club_name in our database and those that don't link to a rider id don't. I'm assuming in these cases you take the last known club for that rider and populate it into the ride table?

But if that is the case, I don't understand why some riders seem to have a rider id and a known club name on their CTT profile page yet we don' know it?

The reason I'm interested in this is purely for calculation of team results as knowledge of club names will affect who counts for a team.

The other thing that I've realised as a result of this is that we are currently displaying on an event's results page the rider's club name if the ride's club name is blank. This is clearly going to become unsafe as time goes by and riders change club. I think we have to use the rider's club name to populate the club name on the ride so that it is retained once they have changed club. I'm wondering if I need to write some SQL to populate these properly into the past as far as we can.

**Comment by drnickw** [comment]
Hi Roger,
I’m on holiday this week up in Scotland.
I will be fine to do the upload on Wednesday.
I may have a chance to check out the club names. 
There is probably an issue between the startsheets and the results. I’ll have to check exactly where the database is uploaded with what.
Previously if I haven’t known the club name I’ve left it blank for the latest race, but if subsequently they run another event with the club we think they are with then it updates, but if they run with a new club it won’t. That said, I don’t think I’ll be updating the rides table rides which have already passed.
The other thing I never got to grips with is checking for new clubs and assigning them a district.
The awards look really good. We’ll need to warn people that if their age isn’t provided we may miss them from the age cats (although we can get the ones we can logically deduce).
I’m hoping to write up the 2 club TTs this week too, thanks for doing the spreadsheet.

**Comment by rogernclarke** [comment]
Awards now displaying on rider profile page - would you believe someone has 236 of them!!

I do really need to introduce paging on the rider page for both results and awards.

Other than that I think we now just need you to be able to trigger award generation at the end of your weekly run. the procedure is set up to generate awards for all events that currently don't have any awards so it will pick up whatever events you add.

**Comment by drnickw** [comment]
I’ll check out the trigger when I get home, hopefully it will be working when we run on Wednesday. I can’t see the awards on the events any longer, do I need to refresh?

**Comment by rogernclarke** [comment]
The awards are there except for results loaded in the last run.

**Comment by drnickw** [comment]
Hi Roger,
Can you give me some examples of these issues so i can check up on them?
Nick.

**Comment by rogernclarke** [comment]
Yep, along with a few stats...

2,066 rides have no club name

555 of these have a negative rider_id (my recollection of these riders is that they featured on a result sheet for which there was no online start sheet and the results were published without their records linking to a CTT rider_id. They could have another rider_id but we have no way of knowing e.g. -467!) We can't do anything with these.

The remaining 1,511 are accounted for by 1,021 riders from 278 events.

I've looked at a few rides from the early 2017 events. There are a lot of events with just one or two rides missing clubs. For all those I've looked at there is no way of knowing what the rider's club was.

event_id 14553 has 21 missing club names. Of these at least one rider (rider_id 2282) has an event before and after with the same club name so would be reasonable to assume that was his club on the day.

there are some much more recent events where we can certainly determine more club names e.g. event_id 17902. The problem we will have is we can only add the club name when the rider next rides. For this event some of these riders have ridden since and some haven't. They could drip feed in at any time. So when do we re-calculate them and do we then recalculate the awards for every event which has someone's club added? This will only affect team awards.

There is no way of knowing whether it is an event with one or lots of missing club names that could successfully be re-processed to add a club name. So every reprocessing run would have to be for all events with a missing club I guess, or at least all within the last year.

I could probably write some sql to do this.

**Comment by drnickw** [comment]
Quick look,
I do some retrospective club repairs on the file but i dont actually update
the rides on the database so although I may have more accurate data I`m not
sending it to you.
Have a look at the latest "scoredata" file. Certainly 2282 has full club
details (apart from his first event in 2017)
I can update the rides club field every week if you like.

**Comment by rogernclarke** [comment]
Can you do a one-off push of updated ride club names into dev so I can see how many get resolved?

**Comment by drnickw** [comment]
Currently in Edinburgh but will try and sort this tonight.

**Comment by drnickw** [comment]
Are you sure this is wrong?

14553 was a very early event and rider 2282 hadnt ridden before I dont
think.
17902 looks right. only non clubbed riders are new except -2 Gary Walters
whose ridden several times but never claimed so is still on a  -2!

I sort every rider every week and rationalise everything I can so whenever
its possible to deduct the club I will have.

Of course we wont know when these fields will come good so it does leave
the problem of them not being assigned. I dont think we can accommodate
retrospective changes to team results. If people want them to be right they
need to make sure they claim their events and let us know if their data is
wrong eg, I think Gary Walters has now claimed the Classics round 2 so has
one race to his name with a team. If he lets us know the others are his we
can merge them on his 29258 id.

**Comment by drnickw** [comment]
I`ve sent the command to dev and its updated all the recent awards. Works a
treat. Go live this week?

**Comment by rogernclarke** [comment]
Should be able to go live by Wednesday.
Not sure what i was looking at with rider 2282 but I could have sworn I saw one event for him that was missing his club and wasn't the first one.
Not sure if we are looking at different things with event 17902. If you are looking at live spindata then it fills in the club name from the rider's record (which I think I have to stop doing). If you look on dev you will see the actual data held on the rides table. Rider 358 for example has events before and after with the same club name so should be populated for this ride?
Most of the issue isn't with riders not claiming, it is events organised offline and the subsequent upload of results with no startsheet doesn't populate the clubs. There is no way (or need) for a rider to claim, and we are waiting for a subsequent ride from each rider with their previous club to populate it - that could be months down the line.
If you update club_names for rides missing them weekly then we'd have to decide which events to update team awards for - the stored procedure you call can be set to recalculate awards for any set of events, or there's another one you can call passing in an event id. The former is currently set to populate awards for events which have no awards, but I could set it to populate all events in the last x weeks, or all events in the last x weeks with more than y club names missing. I think it is worth doing something with this as it should be fairly simple to set up and then we can just forget about it as it runs automatically.

The other thing I've thought of is that I haven't put any error handling in the populate_awards procedure so I'm not sure how you would know if something went wrong. I'll look into how to do this and may change it to return an error / success code.

**Comment by drnickw** [comment]
This is the code returned when I ran the mysql
command. <MySQLResult:825243187,41,0> I dont know if it means anything to
you?

I was looking at SD not dev.SD. I see the problem and have worked out whats
wrong.
I have a file which is datavalidation which is updated every week and then
passed to the scoring process. datavalidation has all the missing club
names entered.
What I`m doing in scoreddata is adding scores to the new records and adding
them to the old scored records, but I never update the old scoredata
records, so the deduced clubs arent being added.
If you look at Thomas Garbett 5591 in SPF2 validdata you`ll see his clubs
are right. If you look in SPF3 scoreddata you`ll see they havent been
corrected. I can easily sort this.

If there`s a way of flagging changes you could just re award events which
have had a riders club change? Would you need to do retrospective changes
to ages too?

Couple of ideas for the events page. Since we have start time can we show
it on the starting order page if there`s room. Also could we give a link to
the event on CTT so people can click directly thru to see their startsheet
info if required?

**Comment by rogernclarke** [comment]
In terms of flagging any changes are you able to update the processed_date field for an event which you've updated a ride for? And yes, ages too if that would change a rider's category - are they missing for the same riders as the missing club names?

Another thought I had on missing club names was whether you could scrape them from the rider's profile page on CTT - so if you process an event's results and find the club name missing for a rider try to scrape it from their profile? No idea how feasible that is, and I know some profiles are private.

I'll create separate issues for your suggestions.

**Comment by drnickw** [comment]
I should be able to create a list of all events where a riders age or team
has been updated quite easily and then just update them with the processed
date too.
You dont need to go into the profile to get the team as its on the list of
riders with the matching search characteristics on Find a CTT rider, so i
can do this too but obviously this wont work retrospectively.
I`ll get onto it!

**Comment by rogernclarke** [comment]
Ok, sounds like we have a plan...

- We'll do a retrospective one-off update of missing club names and ages to ride records
- We'll lookup missing ride club names for the current week's events by doing a lookup on the rider search list on CTT
- We'll update the event processed date for every event where you have had to do an update to a ride's club name or age (assuming this is till needed as you won't get ages from the previous step)
- Populate_awards stored procedure will (re)calculate awards for all events without awards and all events with a last processed date since the last ranking update date.


<MySQLResult:825243187,41,0> - I think the zero might be the response from the stored procedure as it returns a zero when I call it. I've changed it to return the string "Return message" so please call it again and confirm that is what you get back.

I'm trying to decide exactly what to return to you. I'm thinking of sending you a message that the call is successful (with the number of events successfully processed) or not and if not to see if I can include the event ids which have failed in the message. Presumably your script can make what I return visible to you when you run the script?

**Comment by drnickw** [comment]
<MySQLResult:1,42,0>

I`m not going to get all this done before Wednesday as you can imagine.
Can we go live without it?

**Comment by drnickw** [comment]
I`ve updated the clubs ages and age cats that I can do safely on Dev. check
it out.
The system is not however robust yet for weekly processing.
If you`re happy I`ll do it for live too, before tomorrows run.
I like the trophies on the results page, but can they be done on the name
line?
I think splitting some riders to 2 lines and some to 1 makes it much harder
to read overall. The results look so neat when all in 1 uniformly spaced
column.
I assume this was done for screenspace on smaller screens?
Perhaps an awards column which could be omitted on a small screen if they
wont fit anywhere else.
I`m not running after work tomorrow so could call in if we need to
coordinate the new features and the update?
Dont know how long it would take to get the system working on your laptop
but it runs thru in 20 mins on mine.

**Comment by rogernclarke** [comment]
Oh, afraid I'm riding the Barnesbury 10 tonight so will have to meet up another time.

**Comment by rogernclarke** [comment]
I think I'm ready to put this live tomorrow evening. I haven't managed to sort out pagination for the list of awards if it is long but the display now works well for all device sizes.

Can you apply the data updates you put on dev to live now?

I still need to take a look at error handling in the stored procedure but it shouldn't fail.

**Comment by drnickw** [comment]
sorry about the delay, i`ll try and get this uploaded into live tonight but
will be after 9pm.

**Comment by drnickw** [comment]
Done just now.

**Comment by rogernclarke** [comment]
That's great. Been out all day (bit longer than expected!). Not sure if I'll get it live this evening now but definitely will tomorrow.

**Comment by rogernclarke** [comment]
No live with an FAQ and post on TTF

Will leave this open until we've got the club name updates and stored procedure error handling sorted out

**Comment by drnickw** [comment]
Nice! I`ll copy the post to the Spindata FB page. thanks.

**Comment by rogernclarke** [comment]
Would like to close this one - we seem to be doing ok without full error handling in the stored procedure that calculates the awards.

What is the status with the club name updates? Do we need to keep that in an issue of its own? I had forgotten about it!

**Comment by drnickw** [comment]
I still need to make sure its rigorous. Its on my list

**Comment by rogernclarke** [comment]
Ok, I'll raise that as a separate issue on here and a separate one for the paging of awards on the rider screen.
