### ISSUE TITLE
Vets Standard results

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#97]
Display vets standard results for everyone aged 40 and over - with new tab on event results page.

I've been taking a look at what is needed for this, and what columns would be needed on what tables...

I've created a tt_veterans_standards table on dev an populated it with data for men for 10 miles. It is actually very easy to link to the right value in this table for each ride and do the calculation at the point that a ride is being displayed. BUT... in light of the vets standards just having changed, and with the potential for them to change at any point in future, either we'd have to store every standard for every range of dates the standards are valid for, or we'd have to store the correct standard on each ride record. I'm therefore drawn towards the latter option of storing the vets standard on each ride record. I can easily work out the standard result at display time though so no need to store that as well.

**Comment by rogernclarke** [comment]
I have a working solution for vets standard results, but it relies on holding a lookup table of vets standard times for each age / gender / distance / duration in the mySQL database. For each ride the standard needs to be looked up from the table and written to the record in the rides table. This could be done by a database trigger on load of each ride record. This therefore requires no processing in R.

A further complication arises with the change of standards at the start of 2019.

I propose that results for standard distances only for 2017 and 2018 have a standard result per ride, but for 2019 onwards all events should have a standard result. I would load the rides for 2017 and 2018 with standard times before changing the lookup table to hold 2019 standard times.

I can probably source the data needed to apply the standards for 2017 and 2018 but would need them to be scraped for all distances for 2019 and loaded to the lookup table.

I need to do a further modification to the code to handle 12 and 24 hour rides.

Do we know if a ride has been done on a trike?

**Comment by rogernclarke** [comment]
Vets standards table has now been populated on dev with all vets standards (all 228,000 records) and all rides have been populated with the relevant standard time / distance. If the load of results to dev all works fine on Wednesday then I'm ready to load to live.

**Comment by drnickw** [comment]
Ah, so you were able to upload from the cvs file? 
Saves me a job. Thanks.
Good luck tomorrow. Hope it’s fast.

**Comment by rogernclarke** [comment]
Vets standards now has an FAQ so closing this as complete
