### ISSUE TITLE
Don't predict for blacklisted riders

### ISSUE THREAD

**Issue by rogernclarke** [rogernclarke/Rankings#98]
Predictions shouldn't be made for blacklisted riders. The following changes are needed:

- R processing must predict placings not including blacklisted riders
- Website display for blacklisted riders on startsheets needs amending (currently has a higher row for blacklisted riders)

**Comment by drnickw** [comment]
I think I fixed this for live but did you do something too?
Slightly strange glitch today as R wouldnt let me put NULL into the fields so I put NA in instead and now the website shows blank rather than a dash. I`ve no idea what went wrong with R as its the same processing which worked fine till today!

**Comment by rogernclarke** [comment]
I've applied my fixes but not sure yours are working as her latest event has a predicted position and time on the rides table for event_id 18298. I can't see an N/A? The blank instead of a hyphen is a change I made and probably isn't related to any change you've made in data values.

**Comment by drnickw** [comment]
Oh well. At least if you’ve got it sorted then the jobs done. It may be better that way as then the data is preserved but not shown. I can stand this down if your fix definitely works.

**Comment by rogernclarke** [comment]
I don't think this is done - I need your processing not to award a predicted position to a blacklisted rider as otherwise it is obvious from the missing position in the list what the predicted placing would be. The only way to make this work is for your processing not to do a prediction for the rider I think.

**Comment by drnickw** [comment]
Should be resolved next time she rides.

**Comment by drnickw** [comment]
looks OK now - shes riding welsh 25 again

**Comment by rogernclarke** [comment]
Great, I'll close this one now then
